# -*- coding: utf-8 -*-
"""Lista2nisston

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U8c3kq2tuGsjMq4hRfTyN4HEepJ5rbph

Q.1
"""

class Circulo:
    def __init__ (self, raio):
        self.raio = raio

    def calcular_area(self):
        area = 3.14 * (self.raio ** 2)
        return area


c1 = Circulo(5)

print(c1.calcular_area())

"""Q.2"""

class Livro:
    def __init__ (self, titulo, autor):
        self.titulo = titulo
        self.autor = autor

    def detalhes(self):
        print(f"Título......: {self.titulo}\nAutor.......: {self.autor}")


livro = Livro("As Crônicas de Nárnia", "C. S. Lewis")

livro.detalhes()

"""Q.3"""

class Retangulo:
    def __init__ (self, base, altura):
        self.base = base
        self.altura = altura

    def calcular_area(self):
        area = self.base * self.altura
        return area


ret = Retangulo(5, 6)

print(ret.calcular_area())

"""Q.4"""

class ContaBancaria:
    def __init__ (self, saldo, titular):
        self.saldo = saldo
        self.titular = titular

    def depositar(self, valor):
        self.saldo += valor
        return self.saldo

    def sacar(self, valor):
        self.saldo -= valor
        return self.saldo


conta1 = ContaBancaria(500, "João")

print(conta1.saldo, conta1.titular)

"""Q.5"""

class Pessoa:
    def __init__ (self, nome, idade):
        self.nome = nome
        self.idade = idade

    def falar(self):
        print(f"Olá, meu nome é {self.nome} e tenho {self.idade} anos.")


pessoa1 = Pessoa("Cebolinha", 7)

pessoa1.falar()

"""Q.6"""

class Produto:
    def __init__ (self, nome, preco, quantidade):
        self.nome = nome
        self.preco = preco
        self.quantidade = quantidade

    def calcular_total(self):
        valor_total = self.preco * self.quantidade
        return f"Produto......: {self.nome}\nQuantidade...: {self.quantidade}\nValor total..: R${valor_total:.2f}"


prod1 = Produto("Lápis", 1.5, 7)

print(prod1.calcular_total())

"""Q.7"""

class Carro:
    def __init__ (self, marca, modelo, ano):
        self.marca = marca
        self.modelo = modelo
        self.ano = ano

    def detalhes(self):
        print(f"Marca.....: {self.marca}\nModelo....: {self.modelo}\nAno.......: {self.ano}")


carro1 = Carro("Tesla", "S", "2020")

carro1.detalhes()

"""Q.8"""

class Aluno:
    def __init__ (self, nome, nota1, nota2):
        self.nome = nome
        self.nota1 = nota1
        self.nota2 = nota2
    def calcular_media(self):
        media = (self.nota1 + self.nota2)/2
        return f"A média de {self.nome} é {media}"

aluno1 = Aluno("Cascão", 7.6, 8.9)

print(aluno1.calcular_media())

"""Q.9"""

class Triangulo:
    def __init__ (self, lado1, lado2, lado3):
        self.lado1 = lado1
        self.lado2 = lado2
        self.lado3 = lado3
    def calcular_perimetro(self):
        perimetro = self.lado1 + self.lado2 + self.lado3
        return f"O perímetro do triângulo é {perimetro}."


triang1 = Triangulo(5, 7, 8)

print(triang1.calcular_perimetro())

"""Q.10"""

class Funcionario:
    def __init__ (self, nome, salario, cargo):
        self.nome = nome
        self.salario = salario
        self.cargo = cargo
    def aumentar_salario(self, percentual):
        self.salario = self.salario + (self.salario * (percentual/100))
        return self.salario


func1 = Funcionario("Seu Cebola", 5000, "Contador")
print(func1.salario)

func1.aumentar_salario(20)
print(func1.salario)