# -*- coding: utf-8 -*-
"""Lista3nisston

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-F6xFdTVmtFrJVRhqzfsfSxGzC6-DIM

Q.1
"""

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))
nota4 = float(input("Digite a quarta nota: "))
nota5 = float(input("Digite a quinta nota: "))

media = (nota1 + nota2 + nota3 + nota4 + nota5) / 5

if media >= 7:
    print(f"Média: {media:.2f}. Aluno APROVADO!")
else:
    print(f"Média: {media:.2f}. Aluno REPROVADO.")

"""Q.2"""

def calcular_fatorial(numero):
    if numero < 0:
        return "O fatorial não está definido para números negativos."
    elif numero == 0:
        return 1
    else:
        fatorial = 1
        for i in range(1, numero + 1):
            fatorial *= i
        return fatorial

numero = int(input("Digite um número inteiro positivo: "))

resultado = calcular_fatorial(numero)

if isinstance(resultado, int):
    print(f"O fatorial de {numero} é {resultado}.")
else:
    print(resultado)

"""Q.3"""

import string

def e_palindromo(frase):
    frase = frase.lower()
    frase = ''.join(frase.split())
    frase = frase.translate(str.maketrans('', '', string.punctuation))
    return frase == frase[::-1]

entrada = input("Digite uma palavra ou frase para verificar se é um palíndromo: ")

if e_palindromo(entrada):
    print(f"'{entrada}' é um palíndromo.")
else:
    print(f"'{entrada}' não é um palíndromo.")

"""Q.4"""

numero = int(input("Digite um número inteiro positivo: "))

if numero < 0:
    print("Por favor, insira um número inteiro positivo.")
else:
    soma = 0

    numero_str = str(numero)

    for digito in numero_str:
        soma += int(digito)

    print(f"A soma dos dígitos de {numero} é {soma}.")

"""Q.5"""

def e_primo(numero):
    if numero <= 1:
        return False
    if numero == 2:
        return True
    for i in range(2, int(numero**0.5) + 1):
        if numero % i == 0:
            return False
    return True

numero = int(input("Digite um número inteiro para verificar se é primo: "))

if e_primo(numero):
    print(f"{numero} é um número primo.")
else:
    print(f"{numero} não é um número primo.")

"""Q.6"""

string = input("Digite uma string para contar as vogais: ")

string = string.lower()

contador_vogais = 0

vogais = "aeiou"


for caractere in string:
    if caractere in vogais:
        contador_vogais += 1

print(f"A quantidade de vogais na string é: {contador_vogais}")

"""Q.7"""

def calcular_imc(peso, altura):

    if peso <= 0 or altura <= 0:
        return "Peso e altura devem ser valores positivos."
    imc = peso / (altura ** 2)
    return imc

peso = float(input("Digite seu peso (em kg): "))
altura = float(input("Digite sua altura (em metros): "))

imc = calcular_imc(peso, altura)

if isinstance(imc, float):
    print(f"Seu IMC é: {imc:.2f}")
else:
    print(imc)

"""Q.8"""

def celsius_para_fahrenheit(celsius):
    return (celsius * 9/5) + 32

def fahrenheit_para_celsius(fahrenheit):
    return (fahrenheit - 32) * 5/9

escolha = input("Escolha a conversão:\n1. Celsius para Fahrenheit\n2. Fahrenheit para Celsius\nDigite o número da opção: ")

escolha = int(escolha)

if escolha == 1:
    celsius = float(input("Digite a temperatura em graus Celsius: "))
    fahrenheit = celsius_para_fahrenheit(celsius)
    print(f"{celsius} graus Celsius são {fahrenheit:.2f} graus Fahrenheit.")
elif escolha == 2:
    fahrenheit = float(input("Digite a temperatura em graus Fahrenheit: "))
    celsius = fahrenheit_para_celsius(fahrenheit)
    print(f"{fahrenheit} graus Fahrenheit são {celsius:.2f} graus Celsius.")
else:
    print("Escolha inválida. Por favor, digite 1 ou 2 para escolher a conversão desejada.")

"""Q.9"""

def somar(a, b):
    return a + b

def subtrair(a, b):
    return a - b

def multiplicar(a, b):
    return a * b

def dividir(a, b):
    if b == 0:
        return "Erro: Divisão por zero."
    return a / b

print("Escolha a operação:")
print("1. Adição")
print("2. Subtração")
print("3. Multiplicação")
print("4. Divisão")

escolha = input("Digite o número da operação desejada: ")

escolha = int(escolha)

numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))

if escolha == 1:
    resultado = somar(numero1, numero2)
    operacao = "adição"
elif escolha == 2:
    resultado = subtrair(numero1, numero2)
    operacao = "subtração"
elif escolha == 3:
    resultado = multiplicar(numero1, numero2)
    operacao = "multiplicação"
elif escolha == 4:
    resultado = dividir(numero1, numero2)
    operacao = "divisão"
else:
    print("Escolha inválida. Por favor, digite um número de 1 a 4 para escolher a operação.")

if isinstance(resultado, (int, float)):
    print(f"O resultado da {operacao} é: {resultado:.2f}")
else:
    print(resultado)

"""Q.10"""

def gerar_sequencia_fibonacci(numero_de_termos):
    termo1, termo2 = 0, 1

    if numero_de_termos <= 0:
        return "O número de termos deve ser maior que zero."
    elif numero_de_termos == 1:
        return [termo1]
    else:
        sequencia = [termo1, termo2]
        for _ in range(2, numero_de_termos):
            proximo_termo = termo1 + termo2
            sequencia.append(proximo_termo)
            termo1, termo2 = termo2, proximo_termo
        return sequencia

numero_de_termos = int(input("Digite o número de termos da sequência de Fibonacci desejados: "))

resultado = gerar_sequencia_fibonacci(numero_de_termos)

if isinstance(resultado, list):
    print(f"A sequência de Fibonacci com {numero_de_termos} termos é: {resultado}")
else:
 print(resultado)